title: PLCopen Notes
description: Notes taken for the motion control standard 'PLCopen IEC61131-3'
show_downloads: false
google_analytics: false
theme: jekyll-theme-cayman
mathjax: true
markdown: kramdown
